### ISSUE TITLE
Hi, I Was Wondering If You Could Add The Song: Unknown Brain - Roots (feat. Attxla)

### ISSUE THREAD

**Issue by MonksRL** [raphaelreal/CustomRocketLeagueAnthems#2]
Hi, I Was Wondering If You Could Add The Song: Unknown Brain - Roots (feat. Attxla)

**Comment by raphaelreal** [comment]
Added ❤

https://github.com/raphaelreal/CustomRocketLeagueAnthems/tree/main/Unknown%20Brain%20-%20Roots
